server:
  port: 9009
spring:
  application:
    name: springBoot-upload
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 47.104.0.152:22122